# SPDX-License-Identifier: MIT

services:
    oai-gnb-basic:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: oai-gnb-basic
        cap_add:
            - SYS_NICE
        cap_drop:
            - ALL
        environment:
            TFG_L4S_UMBRAL_US: ${TFG_L4S_UMBRAL_US:-0}
            TFG_L4S_CTRL: /tmp/tfg_umbral
            TFG_RLC_LOG: ${TFG_RLC_LOG:-/opt/oai-gnb/tfg_rlc.csv}
            TFG_LOG_MS: ${TFG_LOG_MS:-10}
            RFSIM_REALTIME: ${RFSIM_REALTIME:-0}
            USE_ADDITIONAL_OPTIONS: --rfsim --MACRLCs.[0].stats_max_ue 1 --log_config.global_log_options level,nocolor,time ${RUIDO_OPTS_GNB:-}
            ASAN_OPTIONS: detect_leaks=0
        volumes:
            - ./rfsim-rt/nr-softmodem-tfg:/opt/oai-gnb/bin/nr-softmodem
            - ./ran-conf/gnb_24prb.conf:/opt/oai-gnb/etc/gnb.conf
            - ./rfsim-rt/librfsimulator.so:/usr/local/lib/librfsimulator.so:ro
        networks:
            public_net:
                ipv4_address: 192.168.70.153
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue-basic:
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: oai-nr-ue-basic
        privileged: true
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
            - SYS_NICE
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim -r 24 --ssb 24 --numerology 1 -C 3604800000 --rfsimulator.[0].serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time ${RUIDO_OPTS_UE:-}
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-gnb-basic
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nr-ue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.154
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: demo-oai-public-net
        external: true
